#!/usr/bin/env bash

script_path=`dirname $0`
script_name=`basename $0`
pbench_bin="`cd ${script_path}/..; /bin/pwd`"

# source the base script
. "$pbench_bin"/base

# Perftool scripts must provide the following functions
# 1) Install the tool
# 2) Start data collection
# 3) Stop data collection
# 4) post-process the data

# Defaults
tool=pprof
tool_bin=${GOROOT:-/usr}/bin/go
tool_package=golang
group=default
dir="/tmp"
mode=""
iteration="1"
options="none"
interval=60
origin_master="/etc/sysconfig/origin-master"
origin_node="/etc/sysconfig/origin-node"
ose_openshift_master="/etc/sysconfig/atomic-openshift-master"
ose_openshift_node="/etc/sysconfig/atomic-openshift-node"
ose_openshift_master_api="/etc/sysconfig/atomic-openshift-master-api"
ose_openshift_master_controllers="/etc/sysconfig/atomic-openshift-master-controllers"

opts=$(getopt -o d --longoptions "dir:,group:,iteration:,interval:,inventory:,start,stop,install,postprocess" -n "getopt.sh" -- "$@");
eval set -- "$opts"; 
while true ; do 
    case "$1" in 
    --install)
        mode="install"
        shift;
    ;;
    --start)
        mode="start"
        shift;
    ;;
    --stop)
        mode="stop"
        shift;
    ;;
    --postprocess)
        mode="postprocess"
        shift;
    ;;
    -d|--dir)
        shift;
        if [ -n "$1" ]; then
            dir="$1"
            shift
        fi
    ;;
    -g|--group)
        shift;
        if [ -n "$1" ]; then
                group="$1"
                shift
        fi
      ;;
     -i|--iteration)
        shift;
        if [ -n "$1" ]; then
           iteration="$1"
           shift
        fi
      ;;
    --interval)
        shift;
        if [ -n "$1" ]; then 
            interval="$1"
            shift;
        fi
    ;; 
    --inventory)
        shift;
        if [ -n "$1" ]; then
            inventory="$1"
            shift
        fi
    ;;
    --)
        shift;
        break;
    ;;
    *)
        echo "what's this? [$1]"
        shift;
        break;
    ;; 
esac
done 

tool_cmd="$tool_bin $record_opts"
tool_dir="$dir/tools-$group"
tool_output_dir=$tool_dir/$tool # all tools keep data in their tool specific dir
tool_cmd_file="$tool_output_dir/$tool.cmd"
tool_pid_file=$pbench_tmp/$group.$iteration.$tool.pid
tool_output_file=$tool_output_dir/$tool.txt
export PPROF_TMPDIR=$tool_output_dir
declare -a hosts=($(cat $inventory | sed -n '/^\[pprof\]/,/^$/p' | awk 'length {if (NR!=1) {print}}'))

# function to setup openshift master or node file to support web profile, depending
# is it Openshift Enterprise, or upstream Openshift Origin

collect_data() {
    while true; do
        if [ $(systemctl list-unit-files | grep atomic-openshift-master.service | awk {'print $2'}) == "masked" ]; then
            for host in "${hosts[@]}"; do
                echo $host
                oc get --raw /debug/pprof/profile ${host} > profile && $tool_bin tool $tool -text -seconds=$interval -output $PPROF_TMPDIR/${host}/$(date +%Y-%m-%d:%H:%M:%S).txt profile
                oc get --raw /debug/pprof/heap ${host} > heap && $tool_bin tool $tool -text -seconds=$interval -output $PPROF_TMPDIR/${host}/$(date +%Y-%m-%d:%H:%M:%S)_heap.txt heap
            done
        fi
    done
} 

## check if the inventory variable is set correctly
if [[ ! -s "$inventory" ]] || [[ ! -f "$inventory" ]]; then
	echo "Please check if the inventory file exists, is not empty and the inventory variable is not set to a directory"
	exit 1
fi

case "$mode" in 
    install)
        check_install_rpm $tool_package 
    ;; 
    start)
    	for host in "${hosts[@]}"; do
    	    mkdir -p $tool_output_dir/${host}
    	done
        collect_data
    ;; 
    stop)
        # killing pprof processes at end on of itteration 
        for pprof_process in $(ps aux | grep pbench-tool-$tool | grep -v grep | awk '{print $2}'); do kill -9 $pprof_process; done
    ;; 
    postprocess)
        printf "This script does not do any postprocessing\n"
        printf "Data already collected\n" 
        ls -l $tool_output_dir 
    ;; 
esac 
